# ==============================================================================
# Merged Lakeflow Source: ibm_maximo
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/ibm_maximo/ibm_maximo_schemas.py
    ########################################################

    WODETAIL_SCHEMA = StructType(
        [
            StructField("wonum", StringType(), False),
            StructField("siteid", StringType(), False),
            StructField("orgid", StringType(), True),
            StructField("description", StringType(), True),
            StructField("status", StringType(), True),
            StructField("statusdate", StringType(), True),
            StructField("worktype", StringType(), True),
            StructField("priority", LongType(), True),
            StructField("reportdate", StringType(), True),
            StructField("actstart", StringType(), True),
            StructField("actfinish", StringType(), True),
            StructField("schedstart", StringType(), True),
            StructField("schedfinish", StringType(), True),
            StructField("assetnum", StringType(), True),
            StructField("location", StringType(), True),
            StructField("reportedby", StringType(), True),
            StructField("owner", StringType(), True),
            StructField("ownerperson", StringType(), True),
            StructField("ownergroup", StringType(), True),
            StructField("glaccount", StringType(), True),
            StructField("changedate", StringType(), True),
            StructField("changeby", StringType(), True),
            StructField("historyflag", BooleanType(), True),
            StructField("istask", BooleanType(), True),
            StructField("parent", StringType(), True),
        ]
    )

    ASSET_SCHEMA = StructType(
        [
            StructField("assetnum", StringType(), False),
            StructField("siteid", StringType(), False),
            StructField("orgid", StringType(), True),
            StructField("description", StringType(), True),
            StructField("status", StringType(), True),
            StructField("statusdate", StringType(), True),
            StructField("assettype", StringType(), True),
            StructField("location", StringType(), True),
            StructField("parent", StringType(), True),
            StructField("serialnum", StringType(), True),
            StructField("vendor", StringType(), True),
            StructField("manufacturer", StringType(), True),
            StructField("installdate", StringType(), True),
            StructField("warrantyexpdate", StringType(), True),
            StructField("totdowntime", DoubleType(), True),
            StructField("tottimeonsite", DoubleType(), True),
            StructField("changedate", StringType(), True),
            StructField("changeby", StringType(), True),
            StructField("classstructureid", StringType(), True),
            StructField("priority", LongType(), True),
        ]
    )

    PO_SCHEMA = StructType(
        [
            StructField("ponum", StringType(), False),
            StructField("siteid", StringType(), False),
            StructField("orgid", StringType(), True),
            StructField("description", StringType(), True),
            StructField("status", StringType(), True),
            StructField("statusdate", StringType(), True),
            StructField("vendor", StringType(), True),
            StructField("vendorname", StringType(), True),
            StructField("orderdate", StringType(), True),
            StructField("requireddate", StringType(), True),
            StructField("totalcost", DoubleType(), True),
            StructField("currency", StringType(), True),
            StructField("fromsiteid", StringType(), True),
            StructField("tostoreloc", StringType(), True),
            StructField("changedate", StringType(), True),
            StructField("changeby", StringType(), True),
        ]
    )

    INVENTORY_SCHEMA = StructType(
        [
            StructField("itemnum", StringType(), False),
            StructField("storeloc", StringType(), False),
            StructField("siteid", StringType(), False),
            StructField("orgid", StringType(), True),
            StructField("description", StringType(), True),
            StructField("category", StringType(), True),
            StructField("itemtype", StringType(), True),
            StructField("vendor", StringType(), True),
            StructField("unitcost", DoubleType(), True),
            StructField("curbal", DoubleType(), True),
            StructField("orderqty", DoubleType(), True),
            StructField("reorderpoint", DoubleType(), True),
            StructField("maxlevel", DoubleType(), True),
            StructField("minlevel", DoubleType(), True),
            StructField("changedate", StringType(), True),
            StructField("changeby", StringType(), True),
        ]
    )

    INVBAL_SCHEMA = StructType(
        [
            StructField("itemnum", StringType(), False),
            StructField("siteid", StringType(), False),
            StructField("storeloc", StringType(), False),
            StructField("orgid", StringType(), True),
            StructField("lotnum", StringType(), False),
            StructField("binnum", StringType(), False),
            StructField("curbal", DoubleType(), True),
            StructField("stagingbin", BooleanType(), True),
            StructField("changeby", StringType(), True),
            StructField("changedate", StringType(), True),
        ]
    )

    SR_SCHEMA = StructType(
        [
            StructField("ticketid", StringType(), False),
            StructField("siteid", StringType(), False),
            StructField("orgid", StringType(), True),
            StructField("summary", StringType(), True),
            StructField("description", StringType(), True),
            StructField("status", StringType(), True),
            StructField("statusdate", StringType(), True),
            StructField("reportdate", StringType(), True),
            StructField("reportedby", StringType(), True),
            StructField("affectedperson", StringType(), True),
            StructField("owner", StringType(), True),
            StructField("ownergroup", StringType(), True),
            StructField("assetnum", StringType(), True),
            StructField("location", StringType(), True),
            StructField("classstructureid", StringType(), True),
            StructField("changedate", StringType(), True),
            StructField("changeby", StringType(), True),
            StructField("wonum", StringType(), True),
        ]
    )

    PERSON_SCHEMA = StructType(
        [
            StructField("personid", StringType(), False),
            StructField("firstname", StringType(), True),
            StructField("lastname", StringType(), True),
            StructField("displayname", StringType(), True),
            StructField("status", StringType(), True),
            StructField("primaryemail", StringType(), True),
            StructField("primaryphone", StringType(), True),
            StructField("department", StringType(), True),
            StructField("locationsite", StringType(), True),
            StructField("locationorg", StringType(), True),
            StructField("changedate", StringType(), True),
            StructField("changeby", StringType(), True),
            StructField("sms", StringType(), True),
        ]
    )

    LOCATIONS_SCHEMA = StructType(
        [
            StructField("location", StringType(), False),
            StructField("siteid", StringType(), False),
            StructField("orgid", StringType(), True),
            StructField("description", StringType(), True),
            StructField("type", StringType(), True),
            StructField("status", StringType(), True),
            StructField("statusdate", StringType(), True),
            StructField("parent", StringType(), True),
            StructField("systemid", StringType(), True),
            StructField("changedate", StringType(), True),
            StructField("changeby", StringType(), True),
        ]
    )

    ITEM_SCHEMA = StructType(
        [
            StructField("itemnum", StringType(), False),
            StructField("orgid", StringType(), False),
            StructField("description", StringType(), True),
            StructField("itemtype", StringType(), True),
            StructField("status", StringType(), True),
            StructField("unitofmeasure", StringType(), True),
            StructField("commoditygroup", StringType(), True),
            StructField("commodity", StringType(), True),
            StructField("rotating", BooleanType(), True),
            StructField("lottype", StringType(), True),
            StructField("changedate", StringType(), True),
            StructField("changeby", StringType(), True),
        ]
    )


    TABLE_SCHEMAS: dict[str, StructType] = {
        "mxapiwodetail": WODETAIL_SCHEMA,
        "mxapiasset": ASSET_SCHEMA,
        "mxapipo": PO_SCHEMA,
        "mxapiinventory": INVENTORY_SCHEMA,
        "mxapiinvbal": INVBAL_SCHEMA,
        "mxapisr": SR_SCHEMA,
        "mxapiperson": PERSON_SCHEMA,
        "mxapilocations": LOCATIONS_SCHEMA,
        "mxapiitem": ITEM_SCHEMA,
    }

    SUPPORTED_TABLES: list[str] = list(TABLE_SCHEMAS.keys())


    # ---------------------------------------------------------------------------
    # Per-table metadata
    # ---------------------------------------------------------------------------
    #
    # All CDC tables share ``changedate`` as the incremental cursor. Maximo has
    # no native delete-tracking over REST, so CDC tables are upsert-only ("cdc").
    # ``mxapiinvbal`` is a snapshot: balances change constantly and changedate is
    # not reliably exposed on all Maximo versions.

    TABLE_METADATA: dict[str, dict] = {
        "mxapiwodetail": {
            "primary_keys": ["wonum", "siteid"],
            "cursor_field": "changedate",
            "ingestion_type": "cdc",
        },
        "mxapiasset": {
            "primary_keys": ["assetnum", "siteid"],
            "cursor_field": "changedate",
            "ingestion_type": "cdc",
        },
        "mxapipo": {
            "primary_keys": ["ponum", "siteid"],
            "cursor_field": "changedate",
            "ingestion_type": "cdc",
        },
        "mxapiinventory": {
            "primary_keys": ["itemnum", "storeloc", "siteid"],
            "cursor_field": "changedate",
            "ingestion_type": "cdc",
        },
        "mxapiinvbal": {
            "primary_keys": ["itemnum", "storeloc", "siteid", "lotnum", "binnum"],
            "ingestion_type": "snapshot",
        },
        "mxapisr": {
            "primary_keys": ["ticketid", "siteid"],
            "cursor_field": "changedate",
            "ingestion_type": "cdc",
        },
        "mxapiperson": {
            "primary_keys": ["personid"],
            "cursor_field": "changedate",
            "ingestion_type": "cdc",
        },
        "mxapilocations": {
            "primary_keys": ["location", "siteid"],
            "cursor_field": "changedate",
            "ingestion_type": "cdc",
        },
        "mxapiitem": {
            "primary_keys": ["itemnum", "orgid"],
            "cursor_field": "changedate",
            "ingestion_type": "cdc",
        },
    }


    # ---------------------------------------------------------------------------
    # oslc.select field lists — derived from the declared schemas so the request
    # projection always matches the columns the connector expects to parse.
    # ---------------------------------------------------------------------------

    TABLE_SELECT_FIELDS: dict[str, list[str]] = {
        table: [f.name for f in schema.fields]
        for table, schema in TABLE_SCHEMAS.items()
    }


    ########################################################
    # src/databricks/labs/community_connector/sources/ibm_maximo/ibm_maximo.py
    ########################################################

    EPOCH_ISO = "1970-01-01T00:00:00+00:00"
    # A start cursor at or below this threshold is treated as a first run; the
    # connector emits a single open-ended partition instead of thousands of tiny
    # windows spanning decades.
    FIRST_RUN_SENTINEL_THRESHOLD = "2000-01-01T00:00:00+00:00"

    DEFAULT_PAGE_SIZE = 200
    DEFAULT_WINDOW_SECONDS = 86_400  # 1 day
    DEFAULT_LOOKBACK_SECONDS = 300  # 5 minutes

    RETRIABLE_STATUS_CODES = {429, 500, 502, 503, 504}
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 5.0
    REQUEST_TIMEOUT = 60

    _ERROR_BODY_LIMIT = 256


    def _redact_body(text: str) -> str:
        """Truncate and flatten a response body for safe inclusion in errors."""
        if not text:
            return ""
        flattened = text.replace("\r", " ").replace("\n", " ")
        if len(flattened) <= _ERROR_BODY_LIMIT:
            return flattened
        return flattened[:_ERROR_BODY_LIMIT] + "...[truncated]"


    class IbmMaximoLakeflowConnect(LakeflowConnect, SupportsPartitionedStream):
        """LakeflowConnect implementation for IBM Maximo (OSLC REST API).

        Required connection options:
            base_url (alias: host)   Maximo host root, e.g. https://maximo.example.com
            api_key                  API key sent in the ``apikey`` header.

        Optional connection options:
            api_route                ``oslc`` (default, on-prem) or ``api`` (MAS Manage).
            x_public_uri             Value for the ``x-public-uri`` header (MAS Manage).
            page_size                Default ``oslc.pageSize`` (default 200).

        Per-table options:
            window_seconds           Partition window size in seconds (default 86400).
            lookback_seconds         Lookback subtracted from the start cursor
                                     at read time (default 300).
            page_size                Override ``oslc.pageSize`` for this table.
            start_timestamp          ISO-8601 lower bound for the first read when
                                     no offset exists yet (optional).
            max_records_per_batch    Cap for the single-driver snapshot/fallback
                                     path (default 200000).
        """

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)

            host = options.get("base_url") or options.get("host")
            if not host:
                raise ValueError(
                    "IBM Maximo connector requires connection option "
                    "'base_url' (or 'host')"
                )
            self._api_key = options.get("api_key")
            if not self._api_key:
                raise ValueError(
                    "IBM Maximo connector requires connection option 'api_key'"
                )

            self._host = host.rstrip("/")

            route = (options.get("api_route") or "oslc").strip().lower()
            if route not in ("oslc", "api"):
                raise ValueError(
                    f"Unsupported api_route {route!r}; expected 'oslc' or 'api'"
                )
            self._route = route
            self._x_public_uri = options.get("x_public_uri")

            try:
                self._default_page_size = max(
                    1, int(options.get("page_size") or DEFAULT_PAGE_SIZE)
                )
            except (TypeError, ValueError):
                self._default_page_size = DEFAULT_PAGE_SIZE

            # Cap cursors at init time so a trigger never chases new data. The
            # next trigger creates a fresh instance with a newer init time.
            self._init_time = datetime.now(timezone.utc).isoformat()

        # ------------------------------------------------------------------
        # Schema / metadata
        # ------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            return list(SUPPORTED_TABLES)

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            self._validate_table(table_name)
            return dict(TABLE_METADATA[table_name])

        # ------------------------------------------------------------------
        # SupportsPartitionedStream
        # ------------------------------------------------------------------

        def is_partitioned(self, table_name: str) -> bool:
            """Snapshot tables fall back to the single-driver simpleStreamReader."""
            if table_name not in TABLE_METADATA:
                return False
            return TABLE_METADATA[table_name].get("ingestion_type") == "cdc"

        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the high-water mark, capped at init time.

            Capping at init time is what makes ``Trigger.AvailableNow`` converge:
            once the stream drains everything up to ``_init_time``, successive
            ``latest_offset`` calls return the same value and the trigger stops.
            """
            self._validate_table(table_name)
            return {"cursor": self._init_time}

        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Split the ``(start, end]`` changedate range into time windows."""
            self._validate_table(table_name)

            window_seconds = self._parse_int(
                table_options.get("window_seconds"),
                DEFAULT_WINDOW_SECONDS,
                minimum=1,
            )
            lookback_seconds = self._parse_int(
                table_options.get("lookback_seconds"),
                DEFAULT_LOOKBACK_SECONDS,
                minimum=0,
            )

            if start_offset is None and end_offset is None:
                # Batch mode: partition the entire table.
                start_iso = table_options.get("start_timestamp") or EPOCH_ISO
                end_iso = self._init_time
            else:
                start_iso = (start_offset or {}).get("cursor") or EPOCH_ISO
                end_iso = (end_offset or {}).get("cursor") or self._init_time

            start_dt = self._parse_iso(start_iso)
            end_dt = self._parse_iso(end_iso)
            if start_dt >= end_dt:
                return []

            # First run: one open-ended partition rather than decades of windows.
            if start_dt <= self._parse_iso(FIRST_RUN_SENTINEL_THRESHOLD):
                return [{"since": None, "until": end_iso}]

            if lookback_seconds > 0:
                start_dt = start_dt - timedelta(seconds=lookback_seconds)
                start_iso = self._format_iso(start_dt)
                if start_dt >= end_dt:
                    return []

            partitions: list[dict] = []
            cursor_dt = start_dt
            cursor_iso = start_iso
            while cursor_dt < end_dt:
                next_dt = cursor_dt + timedelta(seconds=window_seconds)
                if next_dt > end_dt:
                    next_dt = end_dt
                    next_iso = end_iso
                else:
                    next_iso = self._format_iso(next_dt)
                partitions.append({"since": cursor_iso, "until": next_iso})
                cursor_dt = next_dt
                cursor_iso = next_iso

            return partitions

        def read_partition(
            self,
            table_name: str,
            partition: dict,
            table_options: dict[str, str],
        ) -> Iterator[dict]:
            """Read one ``(since, until]`` changedate window on an executor."""
            self._validate_table(table_name)
            since = partition.get("since")
            until = partition.get("until")
            where = self._build_where(since, until)
            yield from self._read_paginated(table_name, table_options, where)

        # ------------------------------------------------------------------
        # LakeflowConnect.read_table — single-driver path
        # ------------------------------------------------------------------

        def read_table(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Single-driver read: incremental for CDC, full snapshot otherwise."""
            self._validate_table(table_name)
            metadata = TABLE_METADATA[table_name]

            if metadata.get("ingestion_type") == "snapshot":
                return self._read_snapshot(table_name, start_offset, table_options)

            return self._read_incremental(table_name, start_offset, table_options)

        # ------------------------------------------------------------------
        # Read helpers
        # ------------------------------------------------------------------

        def _read_incremental(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Read all changed records in ``(start, init_time]`` in one batch.

            Fallback path for CDC tables when partitioned streaming is not used.
            The cursor is capped at ``_init_time`` so a trigger terminates.
            """
            since = (start_offset or {}).get("cursor")
            if since and self._parse_iso(since) >= self._parse_iso(self._init_time):
                return iter([]), start_offset

            lookback_seconds = self._parse_int(
                table_options.get("lookback_seconds"),
                DEFAULT_LOOKBACK_SECONDS,
                minimum=0,
            )
            if not since:
                since = table_options.get("start_timestamp")

            query_since = since
            if query_since and lookback_seconds > 0:
                query_since = self._format_iso(
                    self._parse_iso(query_since) - timedelta(seconds=lookback_seconds)
                )

            where = self._build_where(query_since, self._init_time)
            max_records = self._parse_int(
                table_options.get("max_records_per_batch"), 200_000, minimum=1
            )
            records = []
            for rec in self._read_paginated(table_name, table_options, where):
                records.append(rec)
                if len(records) >= max_records:
                    break

            end_offset = {"cursor": self._init_time}
            if start_offset and start_offset == end_offset:
                return iter([]), start_offset
            return iter(records), end_offset

        def _read_snapshot(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Full-snapshot read for non-incremental tables (mxapiinvbal).

            Uses a ``{"done": True}`` sentinel so a second call within the same
            ``Trigger.AvailableNow`` trigger short-circuits and the trigger
            terminates (end_offset == start_offset).
            """
            if start_offset and start_offset.get("done"):
                return iter([]), start_offset

            records = list(self._read_paginated(table_name, table_options, where=None))
            return iter(records), {"done": True}

        def _read_paginated(
            self,
            table_name: str,
            table_options: dict[str, str],
            where: str | None,
        ) -> Iterator[dict]:
            """Yield projected records for an object structure, following
            ``responseInfo.nextPage.href`` until pagination is exhausted."""
            osname = table_name
            select_fields = TABLE_SELECT_FIELDS[table_name]
            page_size = self._parse_int(
                table_options.get("page_size"), self._default_page_size, minimum=1
            )

            url = f"{self._host}/maximo/{self._route}/os/{osname}"
            params: dict[str, str] | None = {
                "lean": "1",
                "oslc.pageSize": str(page_size),
                "oslc.select": ",".join(select_fields),
            }
            if where:
                params["oslc.where"] = where
            # CDC cursor field is changedate; ascending sort lets partial reads
            # resume deterministically.
            if TABLE_METADATA[table_name].get("cursor_field"):
                params["oslc.orderBy"] = "+changedate"

            while True:
                resp = self._get_with_retry(url, params)
                if resp.status_code != 200:
                    raise RuntimeError(
                        f"IBM Maximo read failed for {osname!r}: "
                        f"{resp.status_code} {_redact_body(resp.text)}"
                    )
                body = resp.json()
                members = body.get("member") or []
                for raw in members:
                    yield self._project(table_name, raw)

                next_href = (
                    (body.get("responseInfo") or {}).get("nextPage") or {}
                ).get("href")
                if not next_href or not members:
                    return
                # Follow the next-page link verbatim; params already encoded in it.
                url = next_href
                params = None

        def _project(self, table_name: str, raw: dict) -> dict:
            """Project a raw lean record onto the declared schema columns.

            Extra Maximo fields (``href``, ``_rowstamp``, child collections) are
            dropped; declared columns absent from the record default to ``None``.
            """
            return {field: raw.get(field) for field in TABLE_SELECT_FIELDS[table_name]}

        # ------------------------------------------------------------------
        # HTTP layer
        # ------------------------------------------------------------------

        def _headers(self) -> dict[str, str]:
            headers = {
                "apikey": self._api_key,
                "Accept": "application/json",
            }
            if self._x_public_uri:
                headers["x-public-uri"] = self._x_public_uri
            return headers

        def _get_with_retry(
            self, url: str, params: dict[str, str] | None
        ) -> requests.Response:
            """GET with exponential backoff on 429/5xx and transient network errors."""
            backoff = INITIAL_BACKOFF
            resp: requests.Response | None = None
            last_exc: Exception | None = None
            for attempt in range(MAX_RETRIES):
                try:
                    resp = requests.get(
                        url,
                        headers=self._headers(),
                        params=params,
                        timeout=REQUEST_TIMEOUT,
                    )
                except (
                    requests.ConnectionError,
                    requests.Timeout,
                    requests.exceptions.SSLError,
                ) as exc:
                    last_exc = exc
                    if attempt >= MAX_RETRIES - 1:
                        raise
                    time.sleep(backoff)
                    backoff *= 2
                    continue

                if resp.status_code not in RETRIABLE_STATUS_CODES:
                    return resp

                if attempt < MAX_RETRIES - 1:
                    retry_after = resp.headers.get("Retry-After")
                    try:
                        wait = float(retry_after) if retry_after else backoff
                    except (TypeError, ValueError):
                        wait = backoff
                    time.sleep(wait)
                    backoff *= 2

            if resp is None and last_exc is not None:
                raise last_exc
            return resp  # type: ignore[return-value]

        # ------------------------------------------------------------------
        # Helpers
        # ------------------------------------------------------------------

        def _validate_table(self, table_name: str) -> None:
            if table_name not in SUPPORTED_TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {SUPPORTED_TABLES}"
                )

        @staticmethod
        def _build_where(since: str | None, until: str | None) -> str | None:
            """Build an ``oslc.where`` changedate range clause.

            Lower bound is exclusive (``>``) so back-to-back windows are disjoint;
            upper bound is inclusive (``<=``). Returns ``None`` when neither bound
            is set (unbounded read).
            """
            clauses: list[str] = []
            if since:
                clauses.append(f'changedate>"{since}"')
            if until:
                clauses.append(f'changedate<="{until}"')
            if not clauses:
                return None
            return " and ".join(clauses)

        @staticmethod
        def _parse_int(value: Any, default: int, *, minimum: int = 0) -> int:
            try:
                parsed = int(value)
            except (TypeError, ValueError):
                return default
            return parsed if parsed >= minimum else default

        @staticmethod
        def _parse_iso(iso_ts: str) -> datetime:
            normalised = iso_ts.replace("Z", "+00:00")
            try:
                dt = datetime.fromisoformat(normalised)
            except ValueError as e:
                raise ValueError(f"Invalid ISO timestamp {iso_ts!r}") from e
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            return dt.astimezone(timezone.utc)

        @staticmethod
        def _format_iso(dt: datetime) -> str:
            return dt.astimezone(timezone.utc).isoformat()


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = IbmMaximoLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
